// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: protos/user_service/user.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CompanyService_CompanyRegister_FullMethodName = "/CompanyService/CompanyRegister"
	CompanyService_CompanyLogIn_FullMethodName    = "/CompanyService/CompanyLogIn"
	CompanyService_CheckUniqueness_FullMethodName = "/CompanyService/CheckUniqueness"
)

// CompanyServiceClient is the client API for CompanyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompanyServiceClient interface {
	CompanyRegister(ctx context.Context, in *CompanyRegisterRequest, opts ...grpc.CallOption) (*CompanyRegisterResponse, error)
	CompanyLogIn(ctx context.Context, in *CompanyLogInRequest, opts ...grpc.CallOption) (*CompanyLogInResponse, error)
	CheckUniqueness(ctx context.Context, in *CheckUniquenessRequest, opts ...grpc.CallOption) (*CheckUniquenessResponse, error)
}

type companyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanyServiceClient(cc grpc.ClientConnInterface) CompanyServiceClient {
	return &companyServiceClient{cc}
}

func (c *companyServiceClient) CompanyRegister(ctx context.Context, in *CompanyRegisterRequest, opts ...grpc.CallOption) (*CompanyRegisterResponse, error) {
	out := new(CompanyRegisterResponse)
	err := c.cc.Invoke(ctx, CompanyService_CompanyRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyServiceClient) CompanyLogIn(ctx context.Context, in *CompanyLogInRequest, opts ...grpc.CallOption) (*CompanyLogInResponse, error) {
	out := new(CompanyLogInResponse)
	err := c.cc.Invoke(ctx, CompanyService_CompanyLogIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyServiceClient) CheckUniqueness(ctx context.Context, in *CheckUniquenessRequest, opts ...grpc.CallOption) (*CheckUniquenessResponse, error) {
	out := new(CheckUniquenessResponse)
	err := c.cc.Invoke(ctx, CompanyService_CheckUniqueness_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyServiceServer is the server API for CompanyService service.
// All implementations must embed UnimplementedCompanyServiceServer
// for forward compatibility
type CompanyServiceServer interface {
	CompanyRegister(context.Context, *CompanyRegisterRequest) (*CompanyRegisterResponse, error)
	CompanyLogIn(context.Context, *CompanyLogInRequest) (*CompanyLogInResponse, error)
	CheckUniqueness(context.Context, *CheckUniquenessRequest) (*CheckUniquenessResponse, error)
	mustEmbedUnimplementedCompanyServiceServer()
}

// UnimplementedCompanyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCompanyServiceServer struct {
}

func (UnimplementedCompanyServiceServer) CompanyRegister(context.Context, *CompanyRegisterRequest) (*CompanyRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompanyRegister not implemented")
}
func (UnimplementedCompanyServiceServer) CompanyLogIn(context.Context, *CompanyLogInRequest) (*CompanyLogInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompanyLogIn not implemented")
}
func (UnimplementedCompanyServiceServer) CheckUniqueness(context.Context, *CheckUniquenessRequest) (*CheckUniquenessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUniqueness not implemented")
}
func (UnimplementedCompanyServiceServer) mustEmbedUnimplementedCompanyServiceServer() {}

// UnsafeCompanyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanyServiceServer will
// result in compilation errors.
type UnsafeCompanyServiceServer interface {
	mustEmbedUnimplementedCompanyServiceServer()
}

func RegisterCompanyServiceServer(s grpc.ServiceRegistrar, srv CompanyServiceServer) {
	s.RegisterService(&CompanyService_ServiceDesc, srv)
}

func _CompanyService_CompanyRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).CompanyRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_CompanyRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).CompanyRegister(ctx, req.(*CompanyRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyService_CompanyLogIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyLogInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).CompanyLogIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_CompanyLogIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).CompanyLogIn(ctx, req.(*CompanyLogInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyService_CheckUniqueness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUniquenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).CheckUniqueness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_CheckUniqueness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).CheckUniqueness(ctx, req.(*CheckUniquenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompanyService_ServiceDesc is the grpc.ServiceDesc for CompanyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompanyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CompanyService",
	HandlerType: (*CompanyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompanyRegister",
			Handler:    _CompanyService_CompanyRegister_Handler,
		},
		{
			MethodName: "CompanyLogIn",
			Handler:    _CompanyService_CompanyLogIn_Handler,
		},
		{
			MethodName: "CheckUniqueness",
			Handler:    _CompanyService_CheckUniqueness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/user_service/user.proto",
}
